# ICE Arrests Analysis
**Analyst:** Juan Xavier Gomez Illingworth

**NB:** Parts of the code were constructed with the assistance of Gen AI.

In [21]:
# Load ICE arrests dataset from GitHub
import pandas as pd
import numpy as np
import requests
from io import BytesIO
import plotly.graph_objects as go
import altair as alt
import json

url = "https://github.com/deportationdata/ice/raw/refs/heads/main/data/arrests-latest.xlsx"
response = requests.get(url)
df = pd.read_excel(BytesIO(response.content))

df.head()

,apprehension_date,apprehension_state,apprehension_aor,final_program,final_program_group,apprehension_method,apprehension_criminality,case_status,case_category,departed_date,...,birth_year,citizenship_country,gender,apprehension_site_landmark,unique_identifier,apprehension_date_time,duplicate_likely,file_original,sheet_original,row_original
0,2023-09-01,CALIFORNIA,San Francisco Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Federal Incarceration,1 Convicted Criminal,6-Deported/Removed - Deportability,[16] Reinstated Final Order,2023-09-02,...,1972.0,MEXICO,Male,"FRE GENERAL AREA, NON-SPECIFIC",318f563c52ac3db183b7c613b695e5c836c2942d,2023-09-01 00:00:00,0.0,ERO Admin Arrests_LESA-STU-FINAL Release_raw.xlsx,Admin Arrests,71951
1,2023-09-01,SOUTH CAROLINA,Atlanta Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,2 Pending Criminal Charges,8-Excluded/Removed - Inadmissibility,[8C] Excludable / Inadmissible - Administrativ...,2024-01-17,...,1994.0,HONDURAS,Male,"RICHLAND COUNTY, SC",85fae4868da6f2b760fa10d5bdaf38c08fc3c372,2023-09-01 00:00:00,0.0,ERO Admin Arrests_LESA-STU-FINAL Release_raw.xlsx,Admin Arrests,194383
2,2023-09-01,NaN,NaN,Alternatives to Detention,ICE,ERO Reprocessed Arrest,3 Other Immigration Violator,E-Charging Document Canceled by ICE,[8A] Excludable / Inadmissible - Hearing Not C...,NaT,...,1966.0,ECUADOR,Male,NaN,d75aa42df32375cd184d043fc7753b169d87dde9,2023-09-01 00:19:00,1.0,ERO Admin Arrests_LESA-STU-FINAL Release_raw.xlsx,Admin Arrests,312924
3,2023-09-01,NaN,NaN,Alternatives to Detention,ICE,ERO Reprocessed Arrest,3 Other Immigration Violator,ACTIVE,[8D] Excludable / Inadmissible - Under Adjudic...,NaT,...,1966.0,ECUADOR,Male,NaN,d75aa42df32375cd184d043fc7753b169d87dde9,2023-09-01 00:19:00,1.0,ERO Admin Arrests_LESA-STU-FINAL Release_raw.xlsx,Admin Arrests,312925
4,2023-09-01,NaN,Phoenix Area of Responsibility,Detained Docket Control,ICE,ERO Reprocessed Arrest,3 Other Immigration Violator,ACTIVE,[8B] Excludable / Inadmissible - Under Adjudic...,NaT,...,1999.0,INDIA,Female,NaN,c73d503df74987246f7fd4342bc3d84fa06d7036,2023-09-01 01:09:44,0.0,ERO Admin Arrests_LESA-STU-FINAL Release_raw.xlsx,Admin Arrests,289496

In [41]:
# Inspect column names and data types
df.columns.tolist()
df.dtypes
df.head(10)

,apprehension_date,apprehension_state,apprehension_aor,final_program,final_program_group,apprehension_method,apprehension_criminality,case_status,case_category,departed_date,...,citizenship_country,gender,apprehension_site_landmark,unique_identifier,apprehension_date_time,duplicate_likely,file_original,sheet_original,row_original,date
0,2023-09-01,CALIFORNIA,San Francisco Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Federal Incarceration,1 Convicted Criminal,6-Deported/Removed - Deportability,[16] Reinstated Final Order,2023-09-02,...,MEXICO,Male,"FRE GENERAL AREA, NON-SPECIFIC",318f563c52ac3db183b7c613b695e5c836c2942d,2023-09-01 00:00:00,0.0,ERO Admin Arrests_LESA-STU-FINAL Release_raw.xlsx,Admin Arrests,71951,2023-09-01
1,2023-09-01,SOUTH CAROLINA,Atlanta Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,2 Pending Criminal Charges,8-Excluded/Removed - Inadmissibility,[8C] Excludable / Inadmissible - Administrativ...,2024-01-17,...,HONDURAS,Male,"RICHLAND COUNTY, SC",85fae4868da6f2b760fa10d5bdaf38c08fc3c372,2023-09-01 00:00:00,0.0,ERO Admin Arrests_LESA-STU-FINAL Release_raw.xlsx,Admin Arrests,194383,2023-09-01
2,2023-09-01,NaN,NaN,Alternatives to Detention,ICE,ERO Reprocessed Arrest,3 Other Immigration Violator,E-Charging Document Canceled by ICE,[8A] Excludable / Inadmissible - Hearing Not C...,NaT,...,ECUADOR,Male,NaN,d75aa42df32375cd184d043fc7753b169d87dde9,2023-09-01 00:19:00,1.0,ERO Admin Arrests_LESA-STU-FINAL Release_raw.xlsx,Admin Arrests,312924,2023-09-01
3,2023-09-01,NaN,NaN,Alternatives to Detention,ICE,ERO Reprocessed Arrest,3 Other Immigration Violator,ACTIVE,[8D] Excludable / Inadmissible - Under Adjudic...,NaT,...,ECUADOR,Male,NaN,d75aa42df32375cd184d043fc7753b169d87dde9,2023-09-01 00:19:00,1.0,ERO Admin Arrests_LESA-STU-FINAL Release_raw.xlsx,Admin Arrests,312925,2023-09-01
4,2023-09-01,NaN,Phoenix Area of Responsibility,Detained Docket Control,ICE,ERO Reprocessed Arrest,3 Other Immigration Violator,ACTIVE,[8B] Excludable / Inadmissible - Under Adjudic...,NaT,...,INDIA,Female,NaN,c73d503df74987246f7fd4342bc3d84fa06d7036,2023-09-01 01:09:44,0.0,ERO Admin Arrests_LESA-STU-FINAL Release_raw.xlsx,Admin Arrests,289496,2023-09-01
5,2023-09-01,NaN,NaN,Non-Detained Docket Control,ICE,ERO Reprocessed Arrest,3 Other Immigration Violator,ACTIVE,[8A] Excludable / Inadmissible - Hearing Not C...,NaT,...,INDIA,Male,NaN,0f9ec6b42a90bd9bc12054e9858bf2ffb44ea97c,2023-09-01 03:31:51,0.0,ERO Admin Arrests_LESA-STU-FINAL Release_raw.xlsx,Admin Arrests,22731,2023-09-01
6,2023-09-01,NaN,NaN,Fugitive Operations,ICE,ERO Reprocessed Arrest,3 Other Immigration Violator,ACTIVE,[8A] Excludable / Inadmissible - Hearing Not C...,NaT,...,INDIA,Male,NaN,1c429379ca42e61600b917c30563ca99dfdd70e0,2023-09-01 03:31:51,0.0,ERO Admin Arrests_LESA-STU-FINAL Release_raw.xlsx,Admin Arrests,41183,2023-09-01
7,2023-09-01,NaN,NaN,Detained Docket Control,ICE,ERO Reprocessed Arrest,3 Other Immigration Violator,ACTIVE,[8B] Excludable / Inadmissible - Under Adjudic...,NaT,...,INDIA,Female,NaN,45934f690ff24f83ab8665e6eeba4781dbf5f4ab,2023-09-01 03:31:51,0.0,ERO Admin Arrests_LESA-STU-FINAL Release_raw.xlsx,Admin Arrests,101007,2023-09-01
8,2023-09-01,NaN,NaN,Fugitive Operations,ICE,ERO Reprocessed Arrest,3 Other Immigration Violator,ACTIVE,[8B] Excludable / Inadmissible - Under Adjudic...,NaT,...,INDIA,Male,NaN,543ffc27ca75b1bc44ec8ca12546a7d4604948c7,2023-09-01 03:31:51,0.0,ERO Admin Arrests_LESA-STU-FINAL Release_raw.xlsx,Admin Arrests,122389,2023-09-01
9,2023-09-01,NaN,NaN,Detained Docket Control,ICE,ERO Reprocessed Arrest,3 Other Immigration Violator,ACTIVE,[8B] Excludable / Inadmissible - Under Adjudic...,NaT,...,INDIA,Female,NaN,d305ff069abc4c1bc795b25b8e7eca3a0ed77bcc,2023-09-01 03:31:51,0.0,ERO Admin Arrests_LESA-STU-FINAL Release_raw.xlsx,Admin Arrests,306571,2023-09-01

In [42]:
# Quick column and sample verification
df.columns.tolist()
df.head()

,apprehension_date,apprehension_state,apprehension_aor,final_program,final_program_group,apprehension_method,apprehension_criminality,case_status,case_category,departed_date,...,citizenship_country,gender,apprehension_site_landmark,unique_identifier,apprehension_date_time,duplicate_likely,file_original,sheet_original,row_original,date
0,2023-09-01,CALIFORNIA,San Francisco Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Federal Incarceration,1 Convicted Criminal,6-Deported/Removed - Deportability,[16] Reinstated Final Order,2023-09-02,...,MEXICO,Male,"FRE GENERAL AREA, NON-SPECIFIC",318f563c52ac3db183b7c613b695e5c836c2942d,2023-09-01 00:00:00,0.0,ERO Admin Arrests_LESA-STU-FINAL Release_raw.xlsx,Admin Arrests,71951,2023-09-01
1,2023-09-01,SOUTH CAROLINA,Atlanta Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,2 Pending Criminal Charges,8-Excluded/Removed - Inadmissibility,[8C] Excludable / Inadmissible - Administrativ...,2024-01-17,...,HONDURAS,Male,"RICHLAND COUNTY, SC",85fae4868da6f2b760fa10d5bdaf38c08fc3c372,2023-09-01 00:00:00,0.0,ERO Admin Arrests_LESA-STU-FINAL Release_raw.xlsx,Admin Arrests,194383,2023-09-01
2,2023-09-01,NaN,NaN,Alternatives to Detention,ICE,ERO Reprocessed Arrest,3 Other Immigration Violator,E-Charging Document Canceled by ICE,[8A] Excludable / Inadmissible - Hearing Not C...,NaT,...,ECUADOR,Male,NaN,d75aa42df32375cd184d043fc7753b169d87dde9,2023-09-01 00:19:00,1.0,ERO Admin Arrests_LESA-STU-FINAL Release_raw.xlsx,Admin Arrests,312924,2023-09-01
3,2023-09-01,NaN,NaN,Alternatives to Detention,ICE,ERO Reprocessed Arrest,3 Other Immigration Violator,ACTIVE,[8D] Excludable / Inadmissible - Under Adjudic...,NaT,...,ECUADOR,Male,NaN,d75aa42df32375cd184d043fc7753b169d87dde9,2023-09-01 00:19:00,1.0,ERO Admin Arrests_LESA-STU-FINAL Release_raw.xlsx,Admin Arrests,312925,2023-09-01
4,2023-09-01,NaN,Phoenix Area of Responsibility,Detained Docket Control,ICE,ERO Reprocessed Arrest,3 Other Immigration Violator,ACTIVE,[8B] Excludable / Inadmissible - Under Adjudic...,NaT,...,INDIA,Female,NaN,c73d503df74987246f7fd4342bc3d84fa06d7036,2023-09-01 01:09:44,0.0,ERO Admin Arrests_LESA-STU-FINAL Release_raw.xlsx,Admin Arrests,289496,2023-09-01

In [43]:
# Preview the raw arrests data before aggregation
df.head()

,apprehension_date,apprehension_state,apprehension_aor,final_program,final_program_group,apprehension_method,apprehension_criminality,case_status,case_category,departed_date,...,citizenship_country,gender,apprehension_site_landmark,unique_identifier,apprehension_date_time,duplicate_likely,file_original,sheet_original,row_original,date
0,2023-09-01,CALIFORNIA,San Francisco Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Federal Incarceration,1 Convicted Criminal,6-Deported/Removed - Deportability,[16] Reinstated Final Order,2023-09-02,...,MEXICO,Male,"FRE GENERAL AREA, NON-SPECIFIC",318f563c52ac3db183b7c613b695e5c836c2942d,2023-09-01 00:00:00,0.0,ERO Admin Arrests_LESA-STU-FINAL Release_raw.xlsx,Admin Arrests,71951,2023-09-01
1,2023-09-01,SOUTH CAROLINA,Atlanta Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,2 Pending Criminal Charges,8-Excluded/Removed - Inadmissibility,[8C] Excludable / Inadmissible - Administrativ...,2024-01-17,...,HONDURAS,Male,"RICHLAND COUNTY, SC",85fae4868da6f2b760fa10d5bdaf38c08fc3c372,2023-09-01 00:00:00,0.0,ERO Admin Arrests_LESA-STU-FINAL Release_raw.xlsx,Admin Arrests,194383,2023-09-01
2,2023-09-01,NaN,NaN,Alternatives to Detention,ICE,ERO Reprocessed Arrest,3 Other Immigration Violator,E-Charging Document Canceled by ICE,[8A] Excludable / Inadmissible - Hearing Not C...,NaT,...,ECUADOR,Male,NaN,d75aa42df32375cd184d043fc7753b169d87dde9,2023-09-01 00:19:00,1.0,ERO Admin Arrests_LESA-STU-FINAL Release_raw.xlsx,Admin Arrests,312924,2023-09-01
3,2023-09-01,NaN,NaN,Alternatives to Detention,ICE,ERO Reprocessed Arrest,3 Other Immigration Violator,ACTIVE,[8D] Excludable / Inadmissible - Under Adjudic...,NaT,...,ECUADOR,Male,NaN,d75aa42df32375cd184d043fc7753b169d87dde9,2023-09-01 00:19:00,1.0,ERO Admin Arrests_LESA-STU-FINAL Release_raw.xlsx,Admin Arrests,312925,2023-09-01
4,2023-09-01,NaN,Phoenix Area of Responsibility,Detained Docket Control,ICE,ERO Reprocessed Arrest,3 Other Immigration Violator,ACTIVE,[8B] Excludable / Inadmissible - Under Adjudic...,NaT,...,INDIA,Female,NaN,c73d503df74987246f7fd4342bc3d84fa06d7036,2023-09-01 01:09:44,0.0,ERO Admin Arrests_LESA-STU-FINAL Release_raw.xlsx,Admin Arrests,289496,2023-09-01

In [44]:
# Build monthly arrest counts from Sept 2023 to Jul 2025
df['date'] = pd.to_datetime(df['apprehension_date'])
start_date = pd.Timestamp('2023-09-01')
end_date = pd.Timestamp('2025-07-31')
df_filtered = df[(df['date'] >= start_date) & (df['date'] <= end_date)].copy()
df_filtered['year_month'] = df_filtered['date'].dt.to_period('M')
monthly_arrests = df_filtered.groupby('year_month').size().reset_index(name='arrests')
monthly_arrests['year_month'] = monthly_arrests['year_month'].dt.to_timestamp()
monthly_arrests['arrests_thousands'] = monthly_arrests['arrests'] / 1000
monthly_arrests.head()
monthly_arrests.tail()

   year_month  arrests  arrests_thousands
18 2025-03-01    18952             18.952
19 2025-04-01    17954             17.954
20 2025-05-01    22749             22.749
21 2025-06-01    30617             30.617
22 2025-07-01    27412             27.412

In [45]:
# Prepare chart-ready monthly data with admin flags
chart_data = monthly_arrests.copy()
chart_data['date'] = pd.to_datetime(chart_data['year_month'])
chart_data['year'] = chart_data['date'].dt.year
chart_data['month_num'] = chart_data['date'].dt.month
chart_data['month_letter'] = chart_data['date'].dt.strftime('%b').str[0]
chart_data['admin'] = chart_data['date'].apply(lambda x: 'Trump' if x >= pd.Timestamp('2025-01-01') else 'Biden')
chart_data['color'] = chart_data['admin'].map({'Biden': '#808080', 'Trump': '#d62728'})
chart_data['x_pos'] = range(len(chart_data))
chart_data[['date', 'month_letter', 'year', 'arrests_thousands', 'admin']].head(12)

         date month_letter  year  arrests_thousands  admin
0  2023-09-01            S  2023             10.698  Biden
1  2023-10-01            O  2023             10.197  Biden
2  2023-11-01            N  2023              9.025  Biden
3  2023-12-01            D  2023              9.944  Biden
4  2024-01-01            J  2024              8.612  Biden
5  2024-02-01            F  2024              9.720  Biden
6  2024-03-01            M  2024              9.775  Biden
7  2024-04-01            A  2024             10.336  Biden
8  2024-05-01            M  2024             10.377  Biden
9  2024-06-01            J  2024              8.671  Biden
10 2024-07-01            J  2024              9.589  Biden
11 2024-08-01            A  2024              9.304  Biden

In [46]:
# Define Economist-style Vega-Lite chart and preview
spec = {
    "$schema": "https://vega.github.io/schema/vega-lite/v6.json",
    "config": {
        "axis": {
            "labelFontSize": 12,
            "titleFontSize": 13,
            "labelFont": "Arial, sans-serif",
            "titleFont": "Arial, sans-serif",
            "domainColor": "black",
            "domainWidth": 1
        },
        "title": {
            "fontSize": 16,
            "fontWeight": "bold",
            "font": "Arial, sans-serif",
            "anchor": "start"
        },
        "view": {
            "stroke": "transparent"
        }
    },
    "width": 800,
    "height": 500,
    "title": {
        "text": "Migrant arrests by Immigration and Customs Enforcement (ICE), '000",
        "subtitle": "Source: Deportation Data Project (DeportationData.com)",
        "anchor": "start"
    },
    "data": {"values": chart_data.to_dict('records')},
    "layer": [
        {
            "mark": {"type": "rule", "strokeWidth": 1, "color": "#e0e0e0"},
            "encoding": {"y": {"datum": 5}, "x": {"datum": -0.5}, "x2": {"datum": 23.4}}
        },
        {
            "mark": {"type": "rule", "strokeWidth": 1, "color": "#e0e0e0"},
            "encoding": {"y": {"datum": 10}, "x": {"datum": -0.5}, "x2": {"datum": 23.4}}
        },
        {
            "mark": {"type": "rule", "strokeWidth": 1, "color": "#e0e0e0"},
            "encoding": {"y": {"datum": 15}, "x": {"datum": -0.5}, "x2": {"datum": 23.4}}
        },
        {
            "mark": {"type": "rule", "strokeWidth": 1, "color": "#e0e0e0"},
            "encoding": {"y": {"datum": 20}, "x": {"datum": -0.5}, "x2": {"datum": 23.4}}
        },
        {
            "mark": {"type": "rule", "strokeWidth": 1, "color": "#e0e0e0"},
            "encoding": {"y": {"datum": 25}, "x": {"datum": -0.5}, "x2": {"datum": 23.4}}
        },
        {
            "mark": {"type": "rule", "strokeWidth": 1, "color": "#e0e0e0"},
            "encoding": {"y": {"datum": 30}, "x": {"datum": -0.5}, "x2": {"datum": 23.4}}
        },
        {
            "mark": {"type": "rule", "strokeWidth": 2, "color": "black"},
            "encoding": {"x": {"datum": 16}, "y": {"datum": 0}, "y2": {"datum": 30}}
        },
        {
            "mark": {"type": "bar", "tooltip": True, "color": "#e3120b", "width": {"band": 0.9}},
            "encoding": {
                "x": {
                    "field": "x_pos",
                    "type": "quantitative",
                    "axis": {
                        "title": None,
                        "labels": False,
                        "ticks": False,
                        "grid": False,
                        "domain": True,
                        "domainColor": "black",
                        "domainWidth": 2,
                        "domainOpacity": 1
                    },
                    "scale": {"domain": [-0.5, 23], "nice": False}
                },
                "y": {
                    "field": "arrests_thousands",
                    "type": "quantitative",
                    "axis": {
                        "title": None,
                        "grid": False,
                        "labels": True,
                        "values": [0, 5, 10, 15, 20, 25, 30],
                        "domain": False,
                        "ticks": False,
                        "orient": "right",
                        "labelAlign": "right",
                        "labelBaseline": "middle",
                        "labelPadding": 6,
                        "labelOffset": -9
                    },
                    "scale": {"domain": [0, 30]}
                },
                "tooltip": [
                    {"field": "date", "type": "temporal", "title": "Month", "format": "%b %Y"},
                    {"field": "arrests_thousands", "type": "quantitative", "title": "Arrests (thousands)", "format": ".1f"}
                ]
            }
        },
        {
            "mark": {"type": "rule", "strokeWidth": 1, "color": "black"},
            "encoding": {"y": {"datum": 0, "type": "quantitative"}, "x": {"datum": -0.5, "type": "quantitative"}, "x2": {"datum": 23.4}}
        },
        {
            "data": {"values": [{"x": -0.5}, {"x": 0.5}, {"x": 1.5}, {"x": 2.5}, {"x": 3.5}, {"x": 4.5}, {"x": 5.5}, {"x": 6.5}, {"x": 7.5}, {"x": 8.5}, {"x": 9.5}, {"x": 10.5}, {"x": 11.5}, {"x": 12.5}, {"x": 13.5}, {"x": 14.5}, {"x": 15.5}, {"x": 16.5}, {"x": 17.5}, {"x": 18.5}, {"x": 19.5}, {"x": 20.5}, {"x": 21.5}, {"x": 22.5}]},
            "mark": {"type": "rule", "strokeWidth": 1, "color": "#000000"},
            "encoding": {"x": {"field": "x", "type": "quantitative", "axis": None}, "y": {"datum": 0}, "y2": {"datum": -0.30}}
        },
        {
            "data": {"values": [{"x": 3.5}, {"x": 15.5}]},
            "mark": {"type": "rule", "strokeWidth": 1, "color": "#000000"},
            "encoding": {"x": {"field": "x", "type": "quantitative", "axis": None}, "y": {"datum": 0}, "y2": {"datum": -0.60}}
        },
        {
            "mark": {"type": "text", "align": "center", "baseline": "top", "dy": 5, "fontSize": 11, "fontWeight": "normal"},
            "encoding": {"x": {"field": "x_pos", "type": "quantitative", "axis": None}, "y": {"datum": 0}, "text": {"field": "month_letter", "type": "nominal"}}
        },
        {
            "data": {"values": [{"year": "2023", "x_pos": 1.5}, {"year": "2024", "x_pos": 9.5}, {"year": "2025", "x_pos": 19}]},
            "mark": {"type": "text", "fontSize": 13, "fontWeight": "bold", "baseline": "top", "dy": 25},
            "encoding": {"x": {"field": "x_pos", "type": "quantitative", "axis": None}, "y": {"datum": 0}, "text": {"field": "year", "type": "nominal"}}
        },
        {
            "data": {"values": [{"label": "Biden", "x_pos": 8}, {"label": "Trump", "x_pos": 19}]},
            "mark": {"type": "text", "fontSize": 14, "fontWeight": "bold", "baseline": "middle"},
            "encoding": {"x": {"field": "x_pos", "type": "quantitative", "axis": None}, "y": {"datum": 27.5}, "text": {"field": "label", "type": "nominal"}}
        }
    ]
}

alt.Chart.from_dict(spec)

alt.LayerChart(...)

In [47]:
# Save reproduced chart spec to JSON
output_file = '../graphs/ice_migrant_arrests_total_economist_reproduced.json'
chart = alt.Chart.from_dict(spec)
chart.save(output_file)
output_file

'../graphs/ice_migrant_arrests_total_economist_reproduced.json'

In [48]:
# Calculate baseline average for Biden months
biden_data = chart_data[chart_data['date'] <= pd.Timestamp('2025-01-31')]
biden_average = biden_data['arrests_thousands'].mean()
pd.DataFrame({'biden_average_thousands': [biden_average], 'month_count': [len(biden_data)]})

   biden_average_thousands  month_count
0                 9.628824           17

In [49]:
# Prepare modified chart data with admin reassignment and deltas
chart_data_modified = chart_data.copy()
chart_data_modified['admin'] = chart_data_modified['date'].apply(lambda x: 'Trump' if x >= pd.Timestamp('2025-02-01') else 'Biden')
chart_data_modified['color'] = chart_data_modified['admin'].map({'Biden': '#4472c4', 'Trump': '#e3120b'})
chart_data_modified['baseline'] = biden_average
chart_data_modified['excess'] = chart_data_modified.apply(lambda row: row['arrests_thousands'] - biden_average if row['admin'] == 'Trump' else None, axis=1)
chart_data_modified[['date', 'month_letter', 'arrests_thousands', 'admin', 'color', 'baseline', 'excess']].head(12)

,date,month_letter,arrests_thousands,admin,color,baseline,excess
0,2023-09-01,S,10.698,Biden,#4472c4,9.628824,NaN
1,2023-10-01,O,10.197,Biden,#4472c4,9.628824,NaN
2,2023-11-01,N,9.025,Biden,#4472c4,9.628824,NaN
3,2023-12-01,D,9.944,Biden,#4472c4,9.628824,NaN
4,2024-01-01,J,8.612,Biden,#4472c4,9.628824,NaN
5,2024-02-01,F,9.720,Biden,#4472c4,9.628824,NaN
6,2024-03-01,M,9.775,Biden,#4472c4,9.628824,NaN
7,2024-04-01,A,10.336,Biden,#4472c4,9.628824,NaN
8,2024-05-01,M,10.377,Biden,#4472c4,9.628824,NaN
9,2024-06-01,J,8.671,Biden,#4472c4,9.628824,NaN
10,2024-07-01,J,9.589,Biden,#4472c4,9.628824,NaN
11,2024-08-01,A,9.304,Biden,#4472c4,9.628824,NaN

In [50]:
# Define modified Vega-Lite chart with admin-specific styling
spec_modified = {
    "$schema": "https://vega.github.io/schema/vega-lite/v6.json",
    "config": {
        "axis": {
            "labelFontSize": 12,
            "titleFontSize": 13,
            "labelFont": "Arial, sans-serif",
            "titleFont": "Arial, sans-serif",
            "domainColor": "black",
            "domainWidth": 1
        },
        "title": {
            "fontSize": 18,
            "fontWeight": "bold",
            "font": "Arial, sans-serif",
            "anchor": "start"
        },
        "view": {
            "stroke": "transparent"
        }
    },
    "width": 800,
    "height": 500,
    "title": {
        "text": "Migrant arrests by Immigration and Customs Enforcement (ICE), '000",
        "subtitle": "Source: Deportation Data Project (DeportationData.com)",
        "anchor": "start"
    },
    "data": {"values": chart_data_modified.to_dict('records')},
    "layer": [
        {"mark": {"type": "rule", "strokeWidth": 1, "color": "#e0e0e0"}, "encoding": {"y": {"datum": 5}, "x": {"datum": -0.5}, "x2": {"datum": 23.4}}},
        {"mark": {"type": "rule", "strokeWidth": 1, "color": "#e0e0e0"}, "encoding": {"y": {"datum": 10}, "x": {"datum": -0.5}, "x2": {"datum": 23.4}}},
        {"mark": {"type": "rule", "strokeWidth": 1, "color": "#e0e0e0"}, "encoding": {"y": {"datum": 15}, "x": {"datum": -0.5}, "x2": {"datum": 23.4}}},
        {"mark": {"type": "rule", "strokeWidth": 1, "color": "#e0e0e0"}, "encoding": {"y": {"datum": 20}, "x": {"datum": -0.5}, "x2": {"datum": 23.4}}},
        {"mark": {"type": "rule", "strokeWidth": 1, "color": "#e0e0e0"}, "encoding": {"y": {"datum": 25}, "x": {"datum": -0.5}, "x2": {"datum": 23.4}}},
        {"mark": {"type": "rule", "strokeWidth": 1, "color": "#e0e0e0"}, "encoding": {"y": {"datum": 30}, "x": {"datum": -0.5}, "x2": {"datum": 23.4}}},
        {"mark": {"type": "rule", "strokeWidth": 2, "color": "black"}, "encoding": {"x": {"datum": 16}, "y": {"datum": 0}, "y2": {"datum": 30}}},
        {
            "transform": [{"filter": "datum.admin == 'Biden'"}],
            "mark": {"type": "bar", "tooltip": True, "color": "#4472c4", "width": {"band": 0.9}},
            "encoding": {
                "x": {
                    "field": "x_pos",
                    "type": "quantitative",
                    "axis": {
                        "title": None,
                        "labels": False,
                        "ticks": False,
                        "grid": False,
                        "domain": True,
                        "domainColor": "black",
                        "domainWidth": 2,
                        "domainOpacity": 1
                    },
                    "scale": {"domain": [-0.5, 23], "nice": False}
                },
                "y": {
                    "field": "arrests_thousands",
                    "type": "quantitative",
                    "axis": {
                        "title": None,
                        "grid": False,
                        "labels": True,
                        "values": [0, 5, 10, 15, 20, 25, 30],
                        "domain": False,
                        "ticks": False,
                        "orient": "right",
                        "labelAlign": "right",
                        "labelBaseline": "middle",
                        "labelPadding": 6,
                        "labelOffset": -9
                    },
                    "scale": {"domain": [0, 30]}
                },
                "tooltip": [
                    {"field": "date", "type": "temporal", "title": "Month", "format": "%b %Y"},
                    {"field": "arrests_thousands", "type": "quantitative", "title": "Total arrests (thousands)", "format": ".1f"}
                ]
            }
        },
        {
            "transform": [{"filter": "datum.admin == 'Trump'"}],
            "mark": {"type": "bar", "tooltip": True, "color": "#e3120b", "width": {"band": 0.9}},
            "encoding": {
                "x": {"field": "x_pos", "type": "quantitative", "axis": None, "scale": {"domain": [-0.5, 23], "nice": False}},
                "y": {
                    "field": "arrests_thousands",
                    "type": "quantitative",
                    "axis": {
                        "title": None,
                        "grid": False,
                        "labels": True,
                        "values": [0, 5, 10, 15, 20, 25, 30],
                        "domain": False,
                        "ticks": False,
                        "orient": "right",
                        "labelAlign": "right",
                        "labelBaseline": "middle",
                        "labelPadding": 6,
                        "labelOffset": -9
                    },
                    "scale": {"domain": [0, 30]}
                },
                "tooltip": [
                    {"field": "date", "type": "temporal", "title": "Month", "format": "%b %Y"},
                    {"field": "arrests_thousands", "type": "quantitative", "title": "Total arrests (thousands)", "format": ".1f"},
                    {"field": "baseline", "type": "quantitative", "title": "Baseline (Biden average Sept 2023 - Jan 2025)", "format": ".2f"},
                    {"field": "excess", "type": "quantitative", "title": "Excess over Biden average", "format": ".2f"}
                ]
            }
        },
        {
            "mark": {"type": "rule", "strokeWidth": 2, "strokeDash": [5, 5], "color": "black", "tooltip": True},
            "encoding": {
                "y": {"datum": biden_average},
                "x": {"datum": -0.5},
                "x2": {"datum": 23.4},
                "tooltip": {"value": f"Baseline (Biden average Sept 2023 - Jan 2025): {biden_average:.2f} thousand"}
            }
        },
        {"mark": {"type": "rule", "strokeWidth": 1, "color": "black"}, "encoding": {"y": {"datum": 0, "type": "quantitative"}, "x": {"datum": -0.5, "type": "quantitative"}, "x2": {"datum": 23.4}}},
        {
            "data": {"values": [{"x": -0.5}, {"x": 0.5}, {"x": 1.5}, {"x": 2.5}, {"x": 3.5}, {"x": 4.5}, {"x": 5.5}, {"x": 6.5}, {"x": 7.5}, {"x": 8.5}, {"x": 9.5}, {"x": 10.5}, {"x": 11.5}, {"x": 12.5}, {"x": 13.5}, {"x": 14.5}, {"x": 15.5}, {"x": 16.5}, {"x": 17.5}, {"x": 18.5}, {"x": 19.5}, {"x": 20.5}, {"x": 21.5}, {"x": 22.5}]},
            "mark": {"type": "rule", "strokeWidth": 1, "color": "#000000"},
            "encoding": {"x": {"field": "x", "type": "quantitative", "axis": None}, "y": {"datum": 0}, "y2": {"datum": -0.30}}
        },
        {
            "data": {"values": [{"x": 3.5}, {"x": 15.5}]},
            "mark": {"type": "rule", "strokeWidth": 1, "color": "#000000"},
            "encoding": {"x": {"field": "x", "type": "quantitative", "axis": None}, "y": {"datum": 0}, "y2": {"datum": -0.60}}
        },
        {
            "mark": {"type": "text", "align": "center", "baseline": "top", "dy": 5, "fontSize": 11, "fontWeight": "normal"},
            "encoding": {"x": {"field": "x_pos", "type": "quantitative", "axis": None}, "y": {"datum": 0}, "text": {"field": "month_letter", "type": "nominal"}}
        },
        {
            "data": {"values": [{"year": "2023", "x_pos": 1.5}, {"year": "2024", "x_pos": 9.5}, {"year": "2025", "x_pos": 19}]},
            "mark": {"type": "text", "fontSize": 13, "fontWeight": "bold", "baseline": "top", "dy": 25},
            "encoding": {"x": {"field": "x_pos", "type": "quantitative", "axis": None}, "y": {"datum": 0}, "text": {"field": "year", "type": "nominal"}}
        },
        {
            "data": {"values": [{"label": "Biden", "x_pos": 8}, {"label": "Trump", "x_pos": 19}]},
            "mark": {"type": "text", "fontSize": 14, "fontWeight": "bold", "baseline": "middle"},
            "encoding": {"x": {"field": "x_pos", "type": "quantitative", "axis": None}, "y": {"datum": 27.5}, "text": {"field": "label", "type": "nominal"}}
        },
        {
            "mark": {"type": "rect", "width": 15, "height": 10, "color": "#4472c4"},
            "encoding": {"x": {"datum": 5}, "y": {"datum": 31.5}}
        },
        {
            "mark": {"type": "text", "align": "left", "baseline": "middle", "dx": 2, "fontSize": 11},
            "encoding": {"x": {"datum": 5.4}, "y": {"datum": 31.5}, "text": {"value": "Biden months"}}
        },
        {
            "mark": {"type": "rect", "width": 15, "height": 10, "color": "#e3120b"},
            "encoding": {"x": {"datum": 9.3}, "y": {"datum": 31.5}}
        },
        {
            "mark": {"type": "text", "align": "left", "baseline": "middle", "dx": 2, "fontSize": 11},
            "encoding": {"x": {"datum": 9.7}, "y": {"datum": 31.5}, "text": {"value": "Trump months"}}
        },
        {
            "mark": {"type": "rule", "strokeWidth": 2, "strokeDash": [5, 5], "color": "black"},
            "encoding": {"x": {"datum": 13.8}, "x2": {"datum": 14.3}, "y": {"datum": 31.5}}
        },
        {
            "mark": {"type": "text", "align": "left", "baseline": "middle", "dx": 2, "fontSize": 11},
            "encoding": {"x": {"datum": 14.6}, "y": {"datum": 31.5}, "text": {"value": "Baseline (Biden average)"}}
        }
    ]
}

chart_modified = alt.Chart.from_dict(spec_modified)
chart_modified

alt.LayerChart(...)

In [51]:
# Save modified chart spec to JSON
output_file_modified = '../graphs/ice_migrant_arrests_total_economist_modified.json'
chart_modified = alt.Chart.from_dict(spec_modified)
chart_modified.save(output_file_modified)
output_file_modified

'../graphs/ice_migrant_arrests_total_economist_modified.json'

In [52]:
# Build combined chart with version selector
combined_spec = {
    "$schema": "https://vega.github.io/schema/vega-lite/v6.json",
    "config": {
        "axis": {
            "labelFontSize": 12,
            "titleFontSize": 13,
            "labelFont": "Arial, sans-serif",
            "titleFont": "Arial, sans-serif",
            "domainColor": "black",
            "domainWidth": 1
        },
        "title": {
            "fontSize": 16,
            "fontWeight": "bold",
            "font": "Arial, sans-serif",
            "anchor": "start"
        },
        "view": {
            "stroke": "transparent"
        }
    },
    "width": 800,
    "height": 550,
    "title": {
        "text": "Migrant arrests by Immigration and Customs Enforcement (ICE), '000",
        "subtitle": "Source: Deportation Data Project (DeportationData.com)",
        "anchor": "start"
    },
    "params": [
        {
            "name": "chart_version",
            "value": "Reproduced",
            "bind": {
                "input": "select",
                "options": ["Reproduced", "Modified"],
                "name": "Chart Version: "
            }
        }
    ],
    "data": {"values": chart_data_modified.to_dict('records')},
    "layer": [
        {"mark": {"type": "rule", "strokeWidth": 1, "color": "#e0e0e0"}, "encoding": {"y": {"datum": 5}, "x": {"datum": -0.5}, "x2": {"datum": 23.4}}},
        {"mark": {"type": "rule", "strokeWidth": 1, "color": "#e0e0e0"}, "encoding": {"y": {"datum": 10}, "x": {"datum": -0.5}, "x2": {"datum": 23.4}}},
        {"mark": {"type": "rule", "strokeWidth": 1, "color": "#e0e0e0"}, "encoding": {"y": {"datum": 15}, "x": {"datum": -0.5}, "x2": {"datum": 23.4}}},
        {"mark": {"type": "rule", "strokeWidth": 1, "color": "#e0e0e0"}, "encoding": {"y": {"datum": 20}, "x": {"datum": -0.5}, "x2": {"datum": 23.4}}},
        {"mark": {"type": "rule", "strokeWidth": 1, "color": "#e0e0e0"}, "encoding": {"y": {"datum": 25}, "x": {"datum": -0.5}, "x2": {"datum": 23.4}}},
        {"mark": {"type": "rule", "strokeWidth": 1, "color": "#e0e0e0"}, "encoding": {"y": {"datum": 30}, "x": {"datum": -0.5}, "x2": {"datum": 23.4}}},
        {"mark": {"type": "rule", "strokeWidth": 2, "color": "black"}, "encoding": {"x": {"datum": 16}, "y": {"datum": 0}, "y2": {"datum": 30}}},
        {
            "transform": [{"filter": "chart_version == 'Reproduced'"}],
            "mark": {"type": "bar", "tooltip": True, "color": "#e3120b", "width": {"band": 0.9}},
            "encoding": {
                "x": {
                    "field": "x_pos",
                    "type": "quantitative",
                    "axis": {
                        "title": None,
                        "labels": False,
                        "ticks": False,
                        "grid": False,
                        "domain": True,
                        "domainColor": "black",
                        "domainWidth": 2,
                        "domainOpacity": 1
                    },
                    "scale": {"domain": [-0.5, 23], "nice": False}
                },
                "y": {
                    "field": "arrests_thousands",
                    "type": "quantitative",
                    "axis": {
                        "title": None,
                        "grid": False,
                        "labels": True,
                        "values": [0, 5, 10, 15, 20, 25, 30],
                        "domain": False,
                        "ticks": False,
                        "orient": "right",
                        "labelAlign": "right",
                        "labelBaseline": "middle",
                        "labelPadding": 6,
                        "labelOffset": -9
                    },
                    "scale": {"domain": [-5, 30]}
                },
                "tooltip": [
                    {"field": "date", "type": "temporal", "title": "Month", "format": "%b %Y"},
                    {"field": "arrests_thousands", "type": "quantitative", "title": "Arrests (thousands)", "format": ".1f"}
                ]
            }
        },
        {
            "transform": [{"filter": "chart_version == 'Modified'"}, {"filter": "datum.admin == 'Biden'"}],
            "mark": {"type": "bar", "tooltip": True, "color": "#4472c4", "width": {"band": 0.9}},
            "encoding": {
                "x": {
                    "field": "x_pos",
                    "type": "quantitative",
                    "axis": {
                        "title": None,
                        "labels": False,
                        "ticks": False,
                        "grid": False,
                        "domain": True,
                        "domainColor": "black",
                        "domainWidth": 2,
                        "domainOpacity": 1
                    },
                    "scale": {"domain": [-0.5, 23], "nice": False}
                },
                "y": {
                    "field": "arrests_thousands",
                    "type": "quantitative",
                    "axis": {
                        "title": None,
                        "grid": False,
                        "labels": True,
                        "values": [0, 5, 10, 15, 20, 25, 30],
                        "domain": False,
                        "ticks": False,
                        "orient": "right",
                        "labelAlign": "right",
                        "labelBaseline": "middle",
                        "labelPadding": 6,
                        "labelOffset": -9
                    },
                    "scale": {"domain": [-5, 30]}
                },
                "tooltip": [
                    {"field": "date", "type": "temporal", "title": "Month", "format": "%b %Y"},
                    {"field": "arrests_thousands", "type": "quantitative", "title": "Total arrests (thousands)", "format": ".1f"}
                ]
            }
        },
        {
            "transform": [{"filter": "chart_version == 'Modified'"}, {"filter": "datum.admin == 'Trump'"}],
            "mark": {"type": "bar", "tooltip": True, "color": "#e3120b", "width": {"band": 0.9}},
            "encoding": {
                "x": {"field": "x_pos", "type": "quantitative", "axis": None, "scale": {"domain": [-0.5, 23], "nice": False}},
                "y": {
                    "field": "arrests_thousands",
                    "type": "quantitative",
                    "axis": {
                        "title": None,
                        "grid": False,
                        "labels": True,
                        "values": [0, 5, 10, 15, 20, 25, 30],
                        "domain": False,
                        "ticks": False,
                        "orient": "right",
                        "labelAlign": "right",
                        "labelBaseline": "middle",
                        "labelPadding": 6,
                        "labelOffset": -9
                    },
                    "scale": {"domain": [-5, 30]}
                },
                "tooltip": [
                    {"field": "date", "type": "temporal", "title": "Month", "format": "%b %Y"},
                    {"field": "arrests_thousands", "type": "quantitative", "title": "Total arrests (thousands)", "format": ".1f"},
                    {"field": "baseline", "type": "quantitative", "title": "Baseline (Biden average Sept 2023 - Jan 2025)", "format": ".2f"},
                    {"field": "excess", "type": "quantitative", "title": "Excess over Biden average", "format": ".2f"}
                ]
            }
        },
        {
            "transform": [{"filter": "chart_version == 'Modified'"}],
            "mark": {"type": "rule", "strokeWidth": 2, "strokeDash": [5, 5], "color": "black", "tooltip": True},
            "encoding": {
                "y": {"datum": biden_average},
                "x": {"datum": -0.5},
                "x2": {"datum": 23.4},
                "tooltip": {"value": f"Baseline (Biden average Sept 2023 - Jan 2025): {biden_average:.2f} thousand"}
            }
        },
        {"mark": {"type": "rule", "strokeWidth": 1, "color": "black"}, "encoding": {"y": {"datum": 0, "type": "quantitative"}, "x": {"datum": -0.5, "type": "quantitative"}, "x2": {"datum": 23.4}}},
        {
            "data": {"values": [{"x": -0.5}, {"x": 0.5}, {"x": 1.5}, {"x": 2.5}, {"x": 3.5}, {"x": 4.5}, {"x": 5.5}, {"x": 6.5}, {"x": 7.5}, {"x": 8.5}, {"x": 9.5}, {"x": 10.5}, {"x": 11.5}, {"x": 12.5}, {"x": 13.5}, {"x": 14.5}, {"x": 15.5}, {"x": 16.5}, {"x": 17.5}, {"x": 18.5}, {"x": 19.5}, {"x": 20.5}, {"x": 21.5}, {"x": 22.5}]},
            "mark": {"type": "rule", "strokeWidth": 1, "color": "#000000"},
            "encoding": {"x": {"field": "x", "type": "quantitative", "axis": None}, "y": {"datum": 0}, "y2": {"datum": -0.30}}
        },
        {
            "data": {"values": [{"x": 3.5}, {"x": 15.5}]},
            "mark": {"type": "rule", "strokeWidth": 1, "color": "#000000"},
            "encoding": {"x": {"field": "x", "type": "quantitative", "axis": None}, "y": {"datum": 0}, "y2": {"datum": -0.60}}
        },
        {
            "mark": {"type": "text", "align": "center", "baseline": "top", "dy": 5, "fontSize": 11, "fontWeight": "normal"},
            "encoding": {"x": {"field": "x_pos", "type": "quantitative", "axis": None}, "y": {"datum": 0}, "text": {"field": "month_letter", "type": "nominal"}}
        },
        {
            "data": {"values": [{"year": "2023", "x_pos": 1.5}, {"year": "2024", "x_pos": 9.5}, {"year": "2025", "x_pos": 19}]},
            "mark": {"type": "text", "fontSize": 13, "fontWeight": "bold", "baseline": "top", "dy": 25},
            "encoding": {"x": {"field": "x_pos", "type": "quantitative", "axis": None}, "y": {"datum": 0}, "text": {"field": "year", "type": "nominal"}}
        },
        {
            "data": {"values": [{"label": "Biden", "x_pos": 8}, {"label": "Trump", "x_pos": 19}]},
            "mark": {"type": "text", "fontSize": 14, "fontWeight": "bold", "baseline": "middle"},
            "encoding": {"x": {"field": "x_pos", "type": "quantitative", "axis": None}, "y": {"datum": 27.5}, "text": {"field": "label", "type": "nominal"}}
        },
        {
            "transform": [{"filter": "chart_version == 'Modified'"}],
            "mark": {"type": "rect", "width": 15, "height": 10, "color": "#4472c4"},
            "encoding": {"x": {"datum": 5}, "y": {"datum": -3.5}}
        },
        {
            "transform": [{"filter": "chart_version == 'Modified'"}],
            "mark": {"type": "text", "align": "left", "baseline": "middle", "dx": 2, "fontSize": 11},
            "encoding": {"x": {"datum": 5.4}, "y": {"datum": -3.5}, "text": {"value": "Biden months"}}
        },
        {
            "transform": [{"filter": "chart_version == 'Modified'"}],
            "mark": {"type": "rect", "width": 15, "height": 10, "color": "#e3120b"},
            "encoding": {"x": {"datum": 9.3}, "y": {"datum": -3.5}}
        },
        {
            "transform": [{"filter": "chart_version == 'Modified'"}],
            "mark": {"type": "text", "align": "left", "baseline": "middle", "dx": 2, "fontSize": 11},
            "encoding": {"x": {"datum": 9.7}, "y": {"datum": -3.5}, "text": {"value": "Trump months"}}
        },
        {
            "transform": [{"filter": "chart_version == 'Modified'"}],
            "mark": {"type": "rule", "strokeWidth": 2, "strokeDash": [5, 5], "color": "black"},
            "encoding": {"x": {"datum": 13.8}, "x2": {"datum": 14.3}, "y": {"datum": -3.5}}
        },
        {
            "transform": [{"filter": "chart_version == 'Modified'"}],
            "mark": {"type": "text", "align": "left", "baseline": "middle", "dx": 2, "fontSize": 11},
            "encoding": {"x": {"datum": 14.6}, "y": {"datum": -3.5}, "text": {"value": "Baseline (Biden average)"}}
        }
    ]
}

chart_combined = alt.Chart.from_dict(combined_spec)
chart_combined

alt.LayerChart(...)

In [53]:
# Save combined chart and patch NaN values to null
output_file_combined = '../graphs/ice_migrant_arrests_total_combined_economist.json'
chart_combined.save(output_file_combined)
with open(output_file_combined, 'r') as f:
    content = f.read()
content = content.replace(': NaN', ': null')
with open(output_file_combined, 'w') as f:
    f.write(content)
output_file_combined

'../graphs/ice_migrant_arrests_total_combined_economist.json'

In [54]:
# Prepare status-based percentage data
df_status = df[(df['date'] >= pd.Timestamp('2023-09-01')) & (df['date'] <= pd.Timestamp('2025-07-31'))].copy()
df_status['year_month'] = df_status['date'].dt.to_period('M')
status_counts = df_status.groupby(['year_month', 'apprehension_criminality']).size().reset_index(name='arrests')
monthly_totals = status_counts.groupby('year_month')['arrests'].sum().reset_index(name='total_arrests')
status_counts = status_counts.merge(monthly_totals, on='year_month')
status_counts['percentage'] = (status_counts['arrests'] / status_counts['total_arrests']) * 100
status_counts['date'] = status_counts['year_month'].dt.to_timestamp()
status_counts['date_str'] = status_counts['date'].dt.strftime('%Y-%m-%d')
status_counts['admin'] = status_counts['date'].apply(lambda x: 'Trump' if x >= pd.Timestamp('2025-01-20') else 'Biden')
category_map = {'1 Convicted Criminal': 'Convicted criminal', '2 Pending Criminal Charges': 'Charges pending', '3 Other Immigration Violator': 'Other violation'}
status_counts['category'] = status_counts['apprehension_criminality'].map(category_map)
color_map = {'Convicted criminal': '#404040', 'Other violation': '#E3120B', 'Charges pending': '#B8B8B8'}
status_counts['color'] = status_counts['category'].map(color_map)
status_counts['x_pos'] = status_counts.groupby('year_month').ngroup()
sort_order_map = {'Charges pending': 1, 'Other violation': 2, 'Convicted criminal': 3}
status_counts['sort_order'] = status_counts['category'].map(sort_order_map)
status_counts['month_letter'] = status_counts['date'].dt.strftime('%b').str[0]
status_counts = status_counts.sort_values(['date', 'apprehension_criminality'])
status_counts = status_counts.drop(columns=['year_month'])
status_counts.head(9)

,apprehension_criminality,arrests,total_arrests,percentage,date,date_str,admin,category,color,x_pos,sort_order,month_letter
0,1 Convicted Criminal,4148,10698,38.773603,2023-09-01,2023-09-01,Biden,Convicted criminal,#404040,0,3,S
1,2 Pending Criminal Charges,1489,10698,13.918489,2023-09-01,2023-09-01,Biden,Charges pending,#B8B8B8,0,1,S
2,3 Other Immigration Violator,5061,10698,47.307908,2023-09-01,2023-09-01,Biden,Other violation,#E3120B,0,2,S
3,1 Convicted Criminal,4428,10197,43.424537,2023-10-01,2023-10-01,Biden,Convicted criminal,#404040,1,3,O
4,2 Pending Criminal Charges,1493,10197,14.641561,2023-10-01,2023-10-01,Biden,Charges pending,#B8B8B8,1,1,O
5,3 Other Immigration Violator,4276,10197,41.933902,2023-10-01,2023-10-01,Biden,Other violation,#E3120B,1,2,O
6,1 Convicted Criminal,4266,9025,47.268698,2023-11-01,2023-11-01,Biden,Convicted criminal,#404040,2,3,N
7,2 Pending Criminal Charges,1481,9025,16.409972,2023-11-01,2023-11-01,Biden,Charges pending,#B8B8B8,2,1,N
8,3 Other Immigration Violator,3278,9025,36.321330,2023-11-01,2023-11-01,Biden,Other violation,#E3120B,2,2,N

In [55]:
# Define percentage breakdown chart
spec_percentage = {
    "$schema": "https://vega.github.io/schema/vega-lite/v6.json",
    "config": {
        "view": {"continuousWidth": 300, "continuousHeight": 300, "stroke": "transparent"},
        "axis": {
            "domainColor": "black",
            "domainWidth": 1,
            "labelFont": "Arial, sans-serif",
            "labelFontSize": 12,
            "titleFont": "Arial, sans-serif",
            "titleFontSize": 13
        },
        "title": {
            "anchor": "start",
            "font": "Arial, sans-serif",
            "fontSize": 16,
            "fontWeight": "bold"
        }
    },
    "width": 800,
    "height": 500,
    "title": {
        "text": "Migrant arrests by ICE, % of total",
        "subtitle": "By status at time of arrest",
        "anchor": "start"
    },
    "data": {"values": status_counts.to_dict('records')},
    "layer": [
        {"mark": {"type": "rule", "strokeWidth": 1, "color": "#e0e0e0"}, "encoding": {"y": {"datum": 20}, "x": {"datum": -0.5}, "x2": {"datum": 23.4}}},
        {"mark": {"type": "rule", "strokeWidth": 1, "color": "#e0e0e0"}, "encoding": {"y": {"datum": 40}, "x": {"datum": -0.5}, "x2": {"datum": 23.4}}},
        {"mark": {"type": "rule", "strokeWidth": 1, "color": "#e0e0e0"}, "encoding": {"y": {"datum": 60}, "x": {"datum": -0.5}, "x2": {"datum": 23.4}}},
        {"mark": {"type": "rule", "strokeWidth": 2, "color": "black"}, "encoding": {"x": {"datum": 16}, "y": {"datum": 0}, "y2": {"datum": 65}}},
        {
            "mark": {"type": "line", "point": {"filled": True, "size": 100, "opacity": 0}, "strokeWidth": 2.5, "tooltip": True},
            "encoding": {
                "x": {
                    "field": "x_pos",
                    "type": "quantitative",
                    "axis": {
                        "title": None,
                        "labels": False,
                        "ticks": False,
                        "grid": False,
                        "domain": True,
                        "domainColor": "black",
                        "domainWidth": 2,
                        "domainOpacity": 1
                    },
                    "scale": {"domain": [-0.5, 23], "nice": False}
                },
                "y": {
                    "field": "percentage",
                    "type": "quantitative",
                    "axis": {
                        "title": None,
                        "grid": False,
                        "labels": True,
                        "values": [0, 20, 40, 60],
                        "domain": False,
                        "ticks": False,
                        "orient": "right",
                        "labelAlign": "right",
                        "labelBaseline": "middle",
                        "labelPadding": 9,
                        "labelOffset": -9
                    },
                    "scale": {"domain": [0, 60]}
                },
                "color": {
                    "field": "category",
                    "type": "nominal",
                    "scale": {"domain": ["Convicted criminal", "Other violation", "Charges pending"], "range": ["#404040", "#E3120B", "#B8B8B8"]},
                    "legend": None
                },
                "detail": {"field": "category", "type": "nominal"},
                "tooltip": [
                    {"field": "date", "type": "temporal", "title": "Month", "format": "%b %Y"},
                    {"field": "category", "type": "nominal", "title": "Status"},
                    {"field": "percentage", "type": "quantitative", "title": "Percentage", "format": ".1f"}
                ]
            }
        },
        {"mark": {"type": "rule", "strokeWidth": 1, "color": "black"}, "encoding": {"y": {"datum": 0, "type": "quantitative"}, "x": {"datum": -0.5, "type": "quantitative"}, "x2": {"datum": 23.4}}},
        {
            "data": {"values": [{"x": -0.5}, {"x": 22.5}]},
            "mark": {"type": "rule", "strokeWidth": 1, "color": "#000000"},
            "encoding": {"x": {"field": "x", "type": "quantitative", "axis": None}, "y": {"datum": 0}, "y2": {"datum": -0.3}}
        },
        {
            "data": {"values": [{"x": 3.5}, {"x": 15.5}]},
            "mark": {"type": "rule", "strokeWidth": 1, "color": "#000000"},
            "encoding": {"x": {"field": "x", "type": "quantitative", "axis": None}, "y": {"datum": 0}, "y2": {"datum": -0.6}}
        },
        {
            "data": {"values": [{"year": "2023", "x_pos": 1.5}, {"year": "2024", "x_pos": 9.5}, {"year": "2025", "x_pos": 19}]},
            "mark": {"type": "text", "fontSize": 13, "fontWeight": "bold", "baseline": "top", "dy": 10},
            "encoding": {"x": {"field": "x_pos", "type": "quantitative", "axis": None}, "y": {"datum": 0}, "text": {"field": "year", "type": "nominal"}}
        },
        {
            "data": {"values": [{"label": "Biden", "x_pos": 8}]},
            "mark": {"type": "text", "fontSize": 14, "fontWeight": "bold", "baseline": "middle"},
            "encoding": {"x": {"field": "x_pos", "type": "quantitative", "axis": None}, "y": {"datum": 62}, "text": {"field": "label", "type": "nominal"}}
        },
        {
            "data": {"values": [{"label": "Trump", "x_pos": 19}]},
            "mark": {"type": "text", "fontSize": 14, "fontWeight": "bold", "baseline": "middle"},
            "encoding": {"x": {"field": "x_pos", "type": "quantitative", "axis": None}, "y": {"datum": 62}, "text": {"field": "label", "type": "nominal"}}
        },
        {
            "data": {"values": [{"label": "Convicted criminal", "x_pos": 4.5, "y": 47}]},
            "mark": {"type": "text", "align": "left", "baseline": "middle", "fontSize": 13, "fontWeight": "normal"},
            "encoding": {"x": {"field": "x_pos", "type": "quantitative", "axis": None}, "y": {"field": "y", "type": "quantitative"}, "text": {"field": "label", "type": "nominal"}}
        },
        {
            "data": {"values": [{"label": "Other violation", "x_pos": 4.5, "y": 33}]},
            "mark": {"type": "text", "align": "left", "baseline": "middle", "fontSize": 13, "fontWeight": "bold"},
            "encoding": {"x": {"field": "x_pos", "type": "quantitative", "axis": None}, "y": {"field": "y", "type": "quantitative"}, "text": {"field": "label", "type": "nominal"}}
        },
        {
            "data": {"values": [{"label": "Charges pending", "x_pos": 4.5, "y": 15}]},
            "mark": {"type": "text", "align": "left", "baseline": "middle", "fontSize": 13, "fontWeight": "normal"},
            "encoding": {"x": {"field": "x_pos", "type": "quantitative", "axis": None}, "y": {"field": "y", "type": "quantitative"}, "text": {"field": "label", "type": "nominal"}}
        }
    ]
}

chart_percentage = alt.Chart.from_dict(spec_percentage)
chart_percentage

alt.LayerChart(...)

In [56]:
# Save percentage chart and patch NaN values to null
output_file_percentage = '../graphs/ice_migrant_arrests_percentage_status_economist_reproduced.json'
chart_percentage.save(output_file_percentage)
with open(output_file_percentage, 'r') as f:
    content = f.read()
content = content.replace(': NaN', ': null')
with open(output_file_percentage, 'w') as f:
    f.write(content)
output_file_percentage

'../graphs/ice_migrant_arrests_percentage_status_economist_reproduced.json'

In [57]:
# Prepare data for stacked values chart
status_counts_stacked = status_counts.copy()
status_counts_stacked['arrests_thousands'] = status_counts_stacked['arrests'] / 1000
stacking_order_map = {'Convicted criminal': 1, 'Other violation': 2, 'Charges pending': 3}
status_counts_stacked['stacking_order'] = status_counts_stacked['category'].map(stacking_order_map)
status_counts_stacked[['date', 'category', 'arrests', 'arrests_thousands', 'x_pos', 'stacking_order']].head(9)

,date,category,arrests,arrests_thousands,x_pos,stacking_order
0,2023-09-01,Convicted criminal,4148,4.148,0,1
1,2023-09-01,Charges pending,1489,1.489,0,3
2,2023-09-01,Other violation,5061,5.061,0,2
3,2023-10-01,Convicted criminal,4428,4.428,1,1
4,2023-10-01,Charges pending,1493,1.493,1,3
5,2023-10-01,Other violation,4276,4.276,1,2
6,2023-11-01,Convicted criminal,4266,4.266,2,1
7,2023-11-01,Charges pending,1481,1.481,2,3
8,2023-11-01,Other violation,3278,3.278,2,2

In [58]:
# Define stacked bar chart
spec_stacked = {
    "$schema": "https://vega.github.io/schema/vega-lite/v6.json",
    "config": {
        "view": {"continuousWidth": 300, "continuousHeight": 300, "stroke": "transparent"},
        "axis": {
            "domainColor": "black",
            "domainWidth": 1,
            "labelFont": "Arial, sans-serif",
            "labelFontSize": 12,
            "titleFont": "Arial, sans-serif",
            "titleFontSize": 13
        },
        "title": {
            "anchor": "start",
            "font": "Arial, sans-serif",
            "fontSize": 16,
            "fontWeight": "bold"
        }
    },
    "width": 800,
    "height": 500,
    "title": {
        "text": "Migrant arrests by ICE, '000",
        "subtitle": "By status at time of arrest | Source: Deportation Data Project (DeportationData.com)",
        "anchor": "start"
    },
    "data": {"values": status_counts_stacked.to_dict('records')},
    "layer": [
        {"mark": {"type": "rule", "strokeWidth": 1, "color": "#e0e0e0"}, "encoding": {"y": {"datum": 5}, "x": {"datum": -0.5}, "x2": {"datum": 23.4}}},
        {"mark": {"type": "rule", "strokeWidth": 1, "color": "#e0e0e0"}, "encoding": {"y": {"datum": 10}, "x": {"datum": -0.5}, "x2": {"datum": 23.4}}},
        {"mark": {"type": "rule", "strokeWidth": 1, "color": "#e0e0e0"}, "encoding": {"y": {"datum": 15}, "x": {"datum": -0.5}, "x2": {"datum": 23.4}}},
        {"mark": {"type": "rule", "strokeWidth": 1, "color": "#e0e0e0"}, "encoding": {"y": {"datum": 20}, "x": {"datum": -0.5}, "x2": {"datum": 23.4}}},
        {"mark": {"type": "rule", "strokeWidth": 1, "color": "#e0e0e0"}, "encoding": {"y": {"datum": 25}, "x": {"datum": -0.5}, "x2": {"datum": 23.4}}},
        {"mark": {"type": "rule", "strokeWidth": 1, "color": "#e0e0e0"}, "encoding": {"y": {"datum": 30}, "x": {"datum": -0.5}, "x2": {"datum": 23.4}}},
        {"mark": {"type": "rule", "strokeWidth": 2, "color": "black"}, "encoding": {"x": {"datum": 16}, "y": {"datum": 0}, "y2": {"datum": 30}}},
        {
            "mark": {"type": "bar", "tooltip": True, "width": {"band": 0.9}},
            "encoding": {
                "x": {
                    "field": "x_pos",
                    "type": "quantitative",
                    "axis": {
                        "title": None,
                        "labels": False,
                        "ticks": False,
                        "grid": False,
                        "domain": True,
                        "domainColor": "black",
                        "domainWidth": 2,
                        "domainOpacity": 1
                    },
                    "scale": {"domain": [-0.5, 23], "nice": False}
                },
                "y": {
                    "field": "arrests_thousands",
                    "type": "quantitative",
                    "stack": "zero",
                    "axis": {
                        "title": None,
                        "grid": False,
                        "labels": True,
                        "values": [0, 5, 10, 15, 20, 25, 30],
                        "domain": False,
                        "ticks": False,
                        "orient": "right",
                        "labelAlign": "right",
                        "labelBaseline": "middle",
                        "labelPadding": 6,
                        "labelOffset": -9
                    },
                    "scale": {"domain": [0, 30]}
                },
                "color": {
                    "field": "category",
                    "type": "nominal",
                    "scale": {"domain": ["Convicted criminal", "Other violation", "Charges pending"], "range": ["#404040", "#E3120B", "#B8B8B8"]},
                    "legend": None
                },
                "order": {"field": "stacking_order", "type": "quantitative"},
                "tooltip": [
                    {"field": "date", "type": "temporal", "title": "Month", "format": "%b %Y"},
                    {"field": "category", "type": "nominal", "title": "Status"},
                    {"field": "arrests_thousands", "type": "quantitative", "title": "Arrests (thousands)", "format": ".1f"}
                ]
            }
        },
        {"mark": {"type": "rule", "strokeWidth": 1, "color": "black"}, "encoding": {"y": {"datum": 0, "type": "quantitative"}, "x": {"datum": -0.5, "type": "quantitative"}, "x2": {"datum": 23.4}}},
        {
            "data": {"values": [{"x": -0.5}, {"x": 0.5}, {"x": 1.5}, {"x": 2.5}, {"x": 3.5}, {"x": 4.5}, {"x": 5.5}, {"x": 6.5}, {"x": 7.5}, {"x": 8.5}, {"x": 9.5}, {"x": 10.5}, {"x": 11.5}, {"x": 12.5}, {"x": 13.5}, {"x": 14.5}, {"x": 15.5}, {"x": 16.5}, {"x": 17.5}, {"x": 18.5}, {"x": 19.5}, {"x": 20.5}, {"x": 21.5}, {"x": 22.5}]},
            "mark": {"type": "rule", "strokeWidth": 1, "color": "#000000"},
            "encoding": {"x": {"field": "x", "type": "quantitative", "axis": None}, "y": {"datum": 0}, "y2": {"datum": -0.3}}
        },
        {
            "data": {"values": [{"x": 3.5}, {"x": 15.5}]},
            "mark": {"type": "rule", "strokeWidth": 1, "color": "#000000"},
            "encoding": {"x": {"field": "x", "type": "quantitative", "axis": None}, "y": {"datum": 0}, "y2": {"datum": -0.6}}
        },
        {
            "mark": {"type": "text", "align": "center", "baseline": "top", "dy": 5, "fontSize": 11, "fontWeight": "normal"},
            "encoding": {"x": {"field": "x_pos", "type": "quantitative", "axis": None}, "y": {"datum": 0}, "text": {"field": "month_letter", "type": "nominal"}}
        },
        {
            "data": {"values": [{"year": "2023", "x_pos": 1.5}, {"year": "2024", "x_pos": 9.5}, {"year": "2025", "x_pos": 19}]},
            "mark": {"type": "text", "fontSize": 13, "fontWeight": "bold", "baseline": "top", "dy": 25},
            "encoding": {"x": {"field": "x_pos", "type": "quantitative", "axis": None}, "y": {"datum": 0}, "text": {"field": "year", "type": "nominal"}}
        },
        {
            "data": {"values": [{"label": "Biden", "x_pos": 8}]},
            "mark": {"type": "text", "fontSize": 14, "fontWeight": "bold", "baseline": "middle"},
            "encoding": {"x": {"field": "x_pos", "type": "quantitative", "axis": None}, "y": {"datum": 27.5}, "text": {"field": "label", "type": "nominal"}}
        },
        {
            "data": {"values": [{"label": "Trump", "x_pos": 19}]},
            "mark": {"type": "text", "fontSize": 14, "fontWeight": "bold", "baseline": "middle"},
            "encoding": {"x": {"field": "x_pos", "type": "quantitative", "axis": None}, "y": {"datum": 27.5}, "text": {"field": "label", "type": "nominal"}}
        },
        {
            "mark": {"type": "rect", "width": 15, "height": 10, "color": "#404040"},
            "encoding": {"x": {"datum": 4.5}, "y": {"datum": -3.5}}
        },
        {
            "mark": {"type": "text", "align": "left", "baseline": "middle", "dx": 2, "fontSize": 11},
            "encoding": {"x": {"datum": 4.9}, "y": {"datum": -3.5}, "text": {"value": "Convicted criminal"}}
        },
        {
            "mark": {"type": "rect", "width": 15, "height": 10, "color": "#E3120B"},
            "encoding": {"x": {"datum": 9.5}, "y": {"datum": -3.5}}
        },
        {
            "mark": {"type": "text", "align": "left", "baseline": "middle", "dx": 2, "fontSize": 11},
            "encoding": {"x": {"datum": 9.9}, "y": {"datum": -3.5}, "text": {"value": "Other violation"}}
        },
        {
            "mark": {"type": "rect", "width": 15, "height": 10, "color": "#B8B8B8"},
            "encoding": {"x": {"datum": 13.8}, "y": {"datum": -3.5}}
        },
        {
            "mark": {"type": "text", "align": "left", "baseline": "middle", "dx": 2, "fontSize": 11},
            "encoding": {"x": {"datum": 14.2}, "y": {"datum": -3.5}, "text": {"value": "Charges pending"}}
        }
    ]
}

chart_stacked = alt.Chart.from_dict(spec_stacked)
chart_stacked

alt.LayerChart(...)

In [59]:
# Save stacked chart and patch NaN values to null
output_file_stacked = '../graphs/ice_migrant_arrests_values_stacked_status_economist_modified.json'
chart_stacked.save(output_file_stacked)
with open(output_file_stacked, 'r') as f:
    content = f.read()
content = content.replace(': NaN', ': null')
with open(output_file_stacked, 'w') as f:
    f.write(content)
output_file_stacked

'../graphs/ice_migrant_arrests_values_stacked_status_economist_modified.json'